=== elistevens/xws-spec/schema.json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "$id": "https://github.com/elistevens/xws-spec/blob/master/schema.json",
    "title": "X-Wing Squadron Format Schema Version 2.0.0",
    "description": "A squadron for the X-Wing Miniatures Game in app-independent format for sharing, saving and moving between apps.",
    "type": "object",
    "required": ["faction","pilots", "version"],
    "additionalProperties" : false,
    "properties": {
        "version": {
            "type": "string",
            "pattern" : "^[0-9]+\\.[0-9]+\\.[0-9]+$",
            "description": "The version of the XWS spec used to create this data"
        },
        "name": {
            "type": "string",
            "description": "The name of the squadron."
        },
        "points": {
            "type": "integer",
            "description": "The total points spent creating this squadron."
        },
        "faction": {
            "type": "string",
            "enum": [ "rebelalliance",
                "galacticempire",
                "scumandvillainy",
                "resistance",
                "firstorder",
                "galacticrepublic",
                "separatistalliance"
            ],
            "description": "The faction this squadron belongs to."
        },
        "description": {
            "type": "string",
            "description": "A description of this squadron."
        },
        "obstacles": {
            "type": "array",
            "description": "Array of three Strings, each being an identifier for the obstacle chosen for tournament use.",
            "maxItems": 3,
            "minItems": 3,
            "items": {
                "type": "string"
            }
        },
        "pilots": {
            "type": "array",
            "description": "The members of this squadron.",
            "items": {
                "type": "object",
                "minItems": 1,
                "required": ["id"],
                "additionalProperties" : false,
                "properties": {
                    "id": {
                        "type": "string",
                        "pattern" : "^[0-9a-z-]+[^-]$"
                    },
                    "points": {
                        "type": "integer",
                        "descrpition": "Total point cost of the pilot plus upgrades. SHOULD be ignored by importing applications unless the XWS source is trusted."
                    },
                    "upgrades": {
                        "type": "object",
                        "patternProperties": {
                            "^[0-9a-z]+$": {
                                "type": "array",
                                "minItems": 1,
                                "items": {
                                    "type": "string",
                                    "pattern" : "^[0-9a-z]+$"
                                }
                            }
                        }
                    },
                    "vendor": {
                        "type": "object",
                        "minProperties": 1,
                        "maxProperties": 1,
                        "description": "An extensible object containing app-specific data. Developers should put extra data here under their own namespace.",
                        "patternProperties": {
                            "^.*$": {
                                "type": "object",
                                "properties": {
                                    "url": {
                                        "type": "string"
                                    },
                                    "builder_url": {
                                        "type": "string"
                                    },
                                    "builder": {
                                        "type": "string"
                                    },
                                    "additionalProperties": true
                                }
                            }
                        }
                    }
                }
            }
        },
        "vendor": {
            "type": "object",
            "minProperties": 1,
            "maxProperties": 1,
            "description": "An extensible object containing app-specific data. Developers should put extra data here under their own namespace.",
            "patternProperties": {
                "^.*$": {
                    "type": "object",
                    "properties": {
                        "url": {
                            "type": "string"
                        },
                        "builder_url": {
                            "type": "string"
                        },
                        "builder": {
                            "type": "string"
                        },
                        "additionalProperties": true
                    }
                }
            }
        }
    }
}

=== elistevens/xws-spec/sample.json
{
    "name": "X-Squad",
    "faction": "separatistalliance",
	"description": "Test xws 2.0.0 data",
	"points": 76,
	"version": "2.0.0",
    "pilots": [
        {
            "id": "bombardmentdrone",
			"points": 44,
            "upgrades": {
				"modification": ["angleddeflectors"],
                "configuration": ["landingstruts"],
                "device": ["drk1probedroids"],
                "sensor": ["trajectorysimulator"]
            }
        },
        {
            "id": "dfs311-vultureclassdroidfighter",
			"points": 32,
            "upgrades": {
                "missile": ["clustermissiles"],
                "modification": ["angleddeflectors"],
                "configuration": ["grapplingstruts"]
            },
			"vendor": {
				"pyxwb2": {
					"url": "https://github.com/minsis/pyxwb2"
				}
			}
        }
    ],
	"vendor": {
		"pyxwb2": {
			"url": "https://github.com/minsis/pyxwb2"
		}
	}
}
